#!/usr/bin/env bash

BOLD=$(tput bold)
RESET=$(tput sgr0)

# exit on error and when undefined variables are accessed
set -euo pipefail

# make sure the current working directory is the repository root
cd "$(dirname "$0")/../../"

usage() {
	echo "Usage: $(basename "${BASH_SOURCE[0]}") [--dry-run] <v8 version (internal)> <ubuntu version number (dd.dd)>"
	exit 1
}

DRY_RUN=false

while [[ "$#" -gt 2 ]]; do
	case "$1" in
	"--dry-run")
		DRY_RUN=true
		shift
		;;
	*)
		usage
		;;
	esac
done

if [[ "$#" -ne 2 ]]; then
	usage
fi

if [[ ! "$1" =~ ^[0-9]+$ ]]; then
	usage
fi
V8_VERSION="$1"

#
# Make sure the local repository ships a V8 build script suitable for building
# <v8 version (internal)>
#
case "$V8_VERSION" in
1)
	ALLOWED_V8_HASH="6a41721a2889b84cb2f3b920fbdc40b96347597a"
	;;
2)
	ALLOWED_V8_HASH="b1f56b4a8a7cf9f707f7966104278777f9994b13"
	;;
*)
	echo "ERROR: Unsupported internal V8 version";
	exit 1
esac

if ! grep --quiet "V8_BASE_REVISION=$ALLOWED_V8_HASH" libs/v8/build.sh; then
	echo "ERROR: The local repository's libs/v8/build.sh script does not build the expected V8 version $V8_VERSION"
	exit 1
fi

if [[ ! "$2" =~ ^[0-9][0-9].[0-9][0-9]$ ]]; then
	usage
fi
UBUNTU_VERSION="$2"

# Remove V8 and Ubuntu version from arguments
shift 2

fail_with_unsupported_combination() {
	echo "ERROR: Unsupported combination of V8 version ($V8_VERSION) and Ubuntu version ($UBUNTU_VERSION)"
	exit 1
}

#
# Specify dependencies
#
APT_DEPENDENCIES=(
	"git" "ca-certificates" "curl" "xz-utils"
	"pkg-config" "libxml2-dev" "build-essential"
)
case "$V8_VERSION" in
1)
	case "$UBUNTU_VERSION" in
	"18.04")
		APT_DEPENDENCIES+=("python")
		;;
	"20.04")
		APT_DEPENDENCIES+=("python2 python-is-python2")
		;;
	*)
		fail_with_unsupported_combination
		;;
	esac
	;;
2)
	case "$UBUNTU_VERSION" in
	"20.04")
		APT_DEPENDENCIES+=("python3")
		;;
	"22.04")
		APT_DEPENDENCIES+=("python3")
		;;
	*)
		fail_with_unsupported_combination
		;;
	esac
	;;
esac

#
# List kept files
#
case "$V8_VERSION" in
1)
	KEEPLIST=(
		"v8"
		"v8/v8"
		"v8/v8/include"
		"v8/v8/include/libplatform"
		"v8/v8/include/libplatform/libplatform-export.h"
		"v8/v8/include/libplatform/v8-tracing.h"
		"v8/v8/include/libplatform/libplatform.h"
		"v8/v8/include/v8-inspector.h"
		"v8/v8/include/v8config.h"
		"v8/v8/include/v8-util.h"
		"v8/v8/include/v8.h"
		"v8/v8/include/v8-version.h"
		"v8/v8/include/v8-profiler.h"
		"v8/v8/include/v8-inspector-protocol.h"
		"v8/v8/include/v8-value-serializer-version.h"
		"v8/v8/include/v8-testing.h"
		"v8/v8/include/v8-version-string.h"
		"v8/v8/include/v8-platform.h"
		"v8/v8/out"
		"v8/v8/out/x64.release"
		"v8/v8/out/x64.release/libicui18n.so"
		"v8/v8/out/x64.release/libicuuc.so"
		"v8/v8/out/x64.release/libv8_libplatform.so"
		"v8/v8/out/x64.release/natives_blob.bin"
		"v8/v8/out/x64.release/libv8.so"
		"v8/v8/out/x64.release/snapshot_blob.bin"
		"v8/v8/out/x64.release/libv8_libbase.so"
		"v8/v8/out/x64.release/icudtl.dat"
	)
	;;
2)
	KEEPLIST=(
		"v8"
		"v8/v8"
		"v8/v8/include"
		"v8/v8/include/libplatform"
		"v8/v8/include/libplatform/libplatform-export.h"
		"v8/v8/include/libplatform/v8-tracing.h"
		"v8/v8/include/libplatform/libplatform.h"
		"v8/v8/include/v8-local-handle.h"
		"v8/v8/include/v8-inspector.h"
		"v8/v8/include/v8config.h"
		"v8/v8/include/v8-debug.h"
		"v8/v8/include/v8-locker.h"
		"v8/v8/include/v8-exception.h"
		"v8/v8/include/v8-fast-api-calls.h"
		"v8/v8/include/v8-value-serializer.h"
		"v8/v8/include/v8-typed-array.h"
		"v8/v8/include/v8-promise.h"
		"v8/v8/include/APIDesign.md"
		"v8/v8/include/v8-microtask-queue.h"
		"v8/v8/include/v8-date.h"
		"v8/v8/include/v8-message.h"
		"v8/v8/include/v8-wasm-trap-handler-win.h"
		"v8/v8/include/v8-array-buffer.h"
		"v8/v8/include/v8-cppgc.h"
		"v8/v8/include/v8-microtask.h"
		"v8/v8/include/v8-unwinder.h"
		"v8/v8/include/v8-unwinder-state.h"
		"v8/v8/include/v8-value.h"
		"v8/v8/include/v8-extension.h"
		"v8/v8/include/v8-function.h"
		"v8/v8/include/js_protocol.pdl"
		"v8/v8/include/v8-isolate.h"
		"v8/v8/include/v8-callbacks.h"
		"v8/v8/include/v8-wasm.h"
		"v8/v8/include/v8-util.h"
		"v8/v8/include/v8-forward.h"
		"v8/v8/include/v8-memory-span.h"
		"v8/v8/include/v8-external.h"
		"v8/v8/include/v8-internal.h"
		"v8/v8/include/v8.h"
		"v8/v8/include/v8-proxy.h"
		"v8/v8/include/v8-data.h"
		"v8/v8/include/v8-function-callback.h"
		"v8/v8/include/v8-object.h"
		"v8/v8/include/v8-context.h"
		"v8/v8/include/v8-traced-handle.h"
		"v8/v8/include/v8-embedder-heap.h"
		"v8/v8/include/cppgc"
		"v8/v8/include/cppgc/trace-trait.h"
		"v8/v8/include/cppgc/heap-consistency.h"
		"v8/v8/include/cppgc/prefinalizer.h"
		"v8/v8/include/cppgc/cross-thread-persistent.h"
		"v8/v8/include/cppgc/allocation.h"
		"v8/v8/include/cppgc/type-traits.h"
		"v8/v8/include/cppgc/ephemeron-pair.h"
		"v8/v8/include/cppgc/member.h"
		"v8/v8/include/cppgc/process-heap-statistics.h"
		"v8/v8/include/cppgc/persistent.h"
		"v8/v8/include/cppgc/source-location.h"
		"v8/v8/include/cppgc/testing.h"
		"v8/v8/include/cppgc/heap-state.h"
		"v8/v8/include/cppgc/macros.h"
		"v8/v8/include/cppgc/custom-space.h"
		"v8/v8/include/cppgc/heap.h"
		"v8/v8/include/cppgc/platform.h"
		"v8/v8/include/cppgc/explicit-management.h"
		"v8/v8/include/cppgc/README.md"
		"v8/v8/include/cppgc/name-provider.h"
		"v8/v8/include/cppgc/garbage-collected.h"
		"v8/v8/include/cppgc/heap-statistics.h"
		"v8/v8/include/cppgc/visitor.h"
		"v8/v8/include/cppgc/internal"
		"v8/v8/include/cppgc/internal/gc-info.h"
		"v8/v8/include/cppgc/internal/compiler-specific.h"
		"v8/v8/include/cppgc/internal/name-trait.h"
		"v8/v8/include/cppgc/internal/finalizer-trait.h"
		"v8/v8/include/cppgc/internal/write-barrier.h"
		"v8/v8/include/cppgc/internal/logging.h"
		"v8/v8/include/cppgc/internal/atomic-entry-flag.h"
		"v8/v8/include/cppgc/internal/caged-heap-local-data.h"
		"v8/v8/include/cppgc/internal/api-constants.h"
		"v8/v8/include/cppgc/internal/pointer-policies.h"
		"v8/v8/include/cppgc/internal/persistent-node.h"
		"v8/v8/include/cppgc/common.h"
		"v8/v8/include/cppgc/sentinel-pointer.h"
		"v8/v8/include/cppgc/object-size-trait.h"
		"v8/v8/include/cppgc/liveness-broker.h"
		"v8/v8/include/cppgc/default-platform.h"
		"v8/v8/include/v8-json.h"
		"v8/v8/include/js_protocol-1.2.json"
		"v8/v8/include/v8-container.h"
		"v8/v8/include/v8-embedder-state-scope.h"
		"v8/v8/include/v8-wasm-trap-handler-posix.h"
		"v8/v8/include/v8-initialization.h"
		"v8/v8/include/v8-maybe.h"
		"v8/v8/include/v8-version.h"
		"v8/v8/include/v8-metrics.h"
		"v8/v8/include/v8-template.h"
		"v8/v8/include/v8-weak-callback-info.h"
		"v8/v8/include/v8-persistent-handle.h"
		"v8/v8/include/v8-snapshot.h"
		"v8/v8/include/v8-profiler.h"
		"v8/v8/include/js_protocol-1.3.json"
		"v8/v8/include/v8-statistics.h"
		"v8/v8/include/v8-script.h"
		"v8/v8/include/v8-inspector-protocol.h"
		"v8/v8/include/v8-value-serializer-version.h"
		"v8/v8/include/v8-primitive-object.h"
		"v8/v8/include/v8-regexp.h"
		"v8/v8/include/v8-primitive.h"
		"v8/v8/include/v8-version-string.h"
		"v8/v8/include/v8-platform.h"
		"v8/v8/out"
		"v8/v8/out/x64.release"
		"v8/v8/out/x64.release/icudtl.dat"
		"v8/v8/out/x64.release/obj"
		"v8/v8/out/x64.release/obj/libv8_monolith.a"
	)
	;;
esac

# Write Dockerfile to directory.
# docker build - (i.e. read from stdin) does not support dockerignore
DOCKERFILE_DIR=$(mktemp --directory)
trap 'rm -rf $DOCKERFILE_DIR' EXIT

cat <<-EOF >"$DOCKERFILE_DIR/Dockerfile"
	FROM ubuntu:$UBUNTU_VERSION AS build-stage

	COPY libs/v8 v8

	ARG DEBIAN_FRONTEND=noninteractive
	SHELL ["/bin/bash", "-c"]
	RUN set -xe; \\
	    # Install dependencies \\
	    apt-get update; \\
	    apt-get install --no-install-recommends -y ${APT_DEPENDENCIES[@]}; \\
	    # Silence git warning \\
	    git config --global advice.detachedHead off; \\
	    # Build V8 \\
	    v8/build.sh; \\
	    # Delete unneeded artifacts \\
	    printf "%s\n" ${KEEPLIST[@]} >/KEEPLIST; \\
	    comm -2 -3 <(find v8 | sort) <(sort KEEPLIST) | xargs rm -rf;

	FROM alpine:3
	COPY --from=build-stage /v8/v8 /v8/v8
EOF

cat <<-EOF >"$DOCKERFILE_DIR/Dockerfile.dockerignore"
	*
	!/libs/v8/build.sh
	!/libs/v8/patches/*
EOF

if [[ "$DRY_RUN" = true ]]; then
	echo "${BOLD}Used Dockerfile${RESET}" 1>&2;
	cat "$DOCKERFILE_DIR/Dockerfile"
	echo "${BOLD}Used .dockerignore${RESET}" 1>&2;
	cat "$DOCKERFILE_DIR/Dockerfile.dockerignore"
	exit 0
fi

# For some reason, the
# COPY --from=build-stage ...
# is cached even if the base image for build-stage changes. For example: when
# first building for 20.04 and then for 22.04, the 22.04 COPY will directly
# copy the contents of the 20.04 build stage. Until we figure out why, use
# --no-cache
sudo docker buildx build \
	--no-cache \
	--tag "roboticserlangen/v8:version-$V8_VERSION-ubuntu-$UBUNTU_VERSION" \
	--file "$DOCKERFILE_DIR/Dockerfile" \
	.
