#!/usr/bin/env bash

BOLD=$(tput bold)
RESET=$(tput sgr0)

# exit on error and when undefined variables are accessed
set -euo pipefail

usage() {
    echo "Usage: $(basename "$BASH_SOURCE") <image tag>"
    exit 1
}

if [[ $# -ne 1 ]]; then
    usage
fi

if [[ -e "libs" ]]; then
    echo "'libs' directory already exists in the current folder. It would be overwritten"
    exit 1
fi
mkdir libs

tag=$1

echo "${BOLD}Pulling 'roboticserlangen/v8:$tag'${RESET}"
docker pull "roboticserlangen/v8:$tag"

echo "${BOLD}Creating container${RESET}"
id="$(docker create roboticserlangen/v8:$tag)"

echo "${BOLD}Copying out V8${RESET}"
docker cp "$id":/v8 - > v8.tar
tar xf v8.tar -C libs

echo "${BOLD}Packaging V8 into 'v8-${tag}.tar.gz'${RESET}"
tar cfz "v8-${tag}.tar.gz" libs

echo "${BOLD}Cleaning up${RESET}"
rm -r libs v8.tar
docker rm -v $id

