local EPS = 1E-12

context("base.math", function()
	test("bound", function()
		assert_equal(math.bound(1, 2, 3), 2)
		assert_equal(math.bound(1, 4, 3), 3)
		assert_equal(math.bound(1, 0, 3), 1)
		assert_equal(math.bound(1, -math.huge, 3), 1)
		assert_equal(math.bound(1, math.huge, 3), 3)
	end)

	test("roundTowards", function()
		assert_equal(math.roundTowards(2.5, 3, 0), 3)
		assert_equal(math.roundTowards(2.4, 3, 0.2), 3)
		assert_equal(math.roundTowards(2.399, 3, 0.2), 2)
		assert_equal(math.roundTowards(2.399, 3, 0.2), 2)
		assert_equal(math.roundTowards(2.449, 3, 0.1), 2)
		assert_equal(math.roundTowards(2.551, 2, 0.1), 3)
		assert_equal(math.roundTowards(1.49, 3, 0.1), 1)
		assert_equal(math.roundTowards(4.51, 3, 0.1), 5)
	end)

	test("roundUpwards", function()
		assert_equal(math.roundUpwards(2, 0.1), 2)
		assert_equal(math.roundUpwards(1.5, 0), 2)
		assert_equal(math.roundUpwards(1.4, 0.1), 2)
		assert_equal(math.roundUpwards(1.39, 0.1), 1)
		assert_equal(math.roundUpwards(2.39, 0.1), 2)
		assert_equal(math.roundUpwards(-2.55, 0.1), -2)
		assert_equal(math.roundUpwards(-2.45, 0), -2)
		assert_equal(math.roundUpwards(-2.61, 0.1), -3)
	end)

	test("round", function ()
		assert_equal(math.round(2.45), 2)
		assert_equal(math.round(2.45, 0), 2)
		assert_equal(math.round(2.45, 1), 2.5)
		assert_equal(math.round(2.45, 2), 2.45)
		assert_equal(math.round(0.0001), 0)
		assert_equal(math.round(0.0001, 0), 0)
		assert_equal(math.round(0.0001, 1), 0)
		assert_equal(math.round(0.0001, 2), 0)
		assert_equal(math.round(0.0001, 3), 0)
		assert_equal(math.round(123, 0), 123)
		assert_equal(math.round(123, -1), 120)
		assert_equal_eps(math.round(123, -2), 100, EPS)
		assert_equal(math.round(2.5, 0), 3)
	end)

	test("uniformRandom", function()
		for _ = 1, 100 do
			local rand = math.uniformRandom()
			assert_greater_than(rand, 0)
			assert_lte(rand, 1)
		end
	end)

	test("solveLin", function ()
		assert_equal(math.solveLin(1, 2), -2)
		assert_equal(math.solveLin(0, 2), nil)
		assert_equal(math.solveLin(2, -1), 0.5)
		assert_equal(math.solveLin(-2, -1), -0.5)
		assert_equal(math.solveLin(4, 2), -0.5)
		assert_equal(math.solveLin(-4, -2), -0.5)
	end)

	test("solveSq", function ()
		local x1, x2 = math.solveSq(1, 0, -1)
		assert_equal(x1, 1)
		assert_equal(x2, -1)

		local x1, x2 = math.solveSq(3, -15, 18)
		assert_equal(x1, 2)
		assert_equal(x2, 3)

		// verify numeric stability
		// (x-a)(x-b) = x*x-(a+b)*x+a*b = 0
		local x1, x2 = math.solveSq(1, -1e9-1e-9, 1e9*1e-9)
		assert_equal(x1, 1e-9)
		assert_equal(x2, 1e9)

		local x1, x2 = math.solveSq(1, 0, 0)
		assert_equal(x1, 0)
		assert_equal(x2, nil)
		local x1, x2 = math.solveSq(1, -2, 1)
		assert_equal(x1, 1)
		assert_equal(x2, nil)
		local x1, x2 = math.solveSq(1, -2, 1)
		assert_equal(x1, 1)
		assert_equal(x2, nil)

		local x1, x2 = math.solveSq(1, 0, 1)
		assert_equal(x1, nil)
		assert_equal(x2, nil)

		local x1, x2 = math.solveSq(0, 1, 2)
		assert_equal(x1, -2)
		assert_equal(x2, nil)

		local x1, x2 = math.solveSq(0, 0, 2)
		assert_equal(x1, nil)
		assert_equal(x2, nil)
	end)

	test("sign", function ()
		assert_equal(math.sign(0), 0)
		assert_equal(math.sign(-0), 0)
		assert_equal(math.sign(-0.01), -1)
		assert_equal(math.sign(0.01), 1)
		assert_equal(math.sign(-100), -1)
		assert_equal(math.sign(100), 1)
	end)

	test("average", function ()
		local array = { 1, 2, 3, 4, 0 }
		assert_equal(math.average(array), 2)
		assert_equal(math.average(array, 1, 5), 2)
		assert_equal(math.average(array, 2, 4), 3)
		assert_equal(math.average(array, 4, 4), 4)
	end)

	test("variance", function ()
		local array = { 1, 2, 3, 4, 0 }
		assert_equal(math.variance(array), 2)
		assert_equal(math.variance(array, 2), 2)
		assert_equal(math.variance(array, nil, 1, 5), 2)
		assert_equal(math.variance(array, 2, 1, 5), 2)
		assert_equal(math.variance(array, nil, 2, 4), 2/3)
		assert_equal(math.variance(array, 3, 2, 4), 2/3)
		assert_equal(math.variance(array, nil, 4, 4), 0)
	end)
end)
