let EPS = 1E-12

context("base.math", function()
	test("bound", function()
		assert_equal(MathUtil.bound(1, 2, 3), 2)
		assert_equal(MathUtil.bound(1, 4, 3), 3)
		assert_equal(MathUtil.bound(1, 0, 3), 1)
		assert_equal(MathUtil.bound(1, -Infinity, 3), 1)
		assert_equal(MathUtil.bound(1, Infinity, 3), 3)
	end)

	test("roundTowards", function()
		assert_equal(Math.roundTowards(2.5, 3, 0), 3)
		assert_equal(Math.roundTowards(2.4, 3, 0.2), 3)
		assert_equal(Math.roundTowards(2.399, 3, 0.2), 2)
		assert_equal(Math.roundTowards(2.399, 3, 0.2), 2)
		assert_equal(Math.roundTowards(2.449, 3, 0.1), 2)
		assert_equal(Math.roundTowards(2.551, 2, 0.1), 3)
		assert_equal(Math.roundTowards(1.49, 3, 0.1), 1)
		assert_equal(Math.roundTowards(4.51, 3, 0.1), 5)
	end)

	test("roundUpwards", function()
		assert_equal(Math.roundUpwards(2, 0.1), 2)
		assert_equal(Math.roundUpwards(1.5, 0), 2)
		assert_equal(Math.roundUpwards(1.4, 0.1), 2)
		assert_equal(Math.roundUpwards(1.39, 0.1), 1)
		assert_equal(Math.roundUpwards(2.39, 0.1), 2)
		assert_equal(Math.roundUpwards(-2.55, 0.1), -2)
		assert_equal(Math.roundUpwards(-2.45, 0), -2)
		assert_equal(Math.roundUpwards(-2.61, 0.1), -3)
	end)

	test("round", function ()
		assert_equal(Math.round(2.45), 2)
		assert_equal(Math.round(2.45, 0), 2)
		assert_equal(Math.round(2.45, 1), 2.5)
		assert_equal(Math.round(2.45, 2), 2.45)
		assert_equal(Math.round(0.0001), 0)
		assert_equal(Math.round(0.0001, 0), 0)
		assert_equal(Math.round(0.0001, 1), 0)
		assert_equal(Math.round(0.0001, 2), 0)
		assert_equal(Math.round(0.0001, 3), 0)
		assert_equal(Math.round(123, 0), 123)
		assert_equal(Math.round(123, -1), 120)
		assert_equal_eps(Math.round(123, -2), 100, EPS)
		assert_equal(Math.round(2.5, 0), 3)
	end)

	test("uniformRandom", function()
		for (_ = 1, 100) {
			let rand = Math.uniformRandom()
			assert_greater_than(rand, 0)
			assert_lte(rand, 1)
		}
	end)

	test("solveLin", function ()
		assert_equal(Math.solveLin(1, 2), -2)
		assert_equal(Math.solveLin(0, 2), undefined)
		assert_equal(Math.solveLin(2, -1), 0.5)
		assert_equal(Math.solveLin(-2, -1), -0.5)
		assert_equal(Math.solveLin(4, 2), -0.5)
		assert_equal(Math.solveLin(-4, -2), -0.5)
	end)

	test("solveSq", function ()
		let x1, x2 = Math.solveSq(1, 0, -1)
		assert_equal(x1, 1)
		assert_equal(x2, -1)

		let x1, x2 = Math.solveSq(3, -15, 18)
		assert_equal(x1, 2)
		assert_equal(x2, 3)

		// verify numeric stability
		// (x-a)(x-b) = x*x-(a+b)*x+a*b = 0
		let x1, x2 = Math.solveSq(1, -1e9-1e-9, 1e9*1e-9)
		assert_equal(x1, 1e-9)
		assert_equal(x2, 1e9)

		let x1, x2 = Math.solveSq(1, 0, 0)
		assert_equal(x1, 0)
		assert_equal(x2, undefined)
		let x1, x2 = Math.solveSq(1, -2, 1)
		assert_equal(x1, 1)
		assert_equal(x2, undefined)
		let x1, x2 = Math.solveSq(1, -2, 1)
		assert_equal(x1, 1)
		assert_equal(x2, undefined)

		let x1, x2 = Math.solveSq(1, 0, 1)
		assert_equal(x1, undefined)
		assert_equal(x2, undefined)

		let x1, x2 = Math.solveSq(0, 1, 2)
		assert_equal(x1, -2)
		assert_equal(x2, undefined)

		let x1, x2 = Math.solveSq(0, 0, 2)
		assert_equal(x1, undefined)
		assert_equal(x2, undefined)
	end)

	test("sign", function ()
		assert_equal(MathUtil.sign(0), 0)
		assert_equal(MathUtil.sign(-0), 0)
		assert_equal(MathUtil.sign(-0.01), -1)
		assert_equal(MathUtil.sign(0.01), 1)
		assert_equal(MathUtil.sign(-100), -1)
		assert_equal(MathUtil.sign(100), 1)
	end)

	test("average", function ()
		let array = { 1, 2, 3, 4, 0 }
		assert_equal(Math.average(array), 2)
		assert_equal(Math.average(array, 1, 5), 2)
		assert_equal(Math.average(array, 2, 4), 3)
		assert_equal(Math.average(array, 4, 4), 4)
	end)

	test("variance", function ()
		let array = { 1, 2, 3, 4, 0 }
		assert_equal(Math.variance(array), 2)
		assert_equal(Math.variance(array, 2), 2)
		assert_equal(Math.variance(array, undefined, 1, 5), 2)
		assert_equal(Math.variance(array, 2, 1, 5), 2)
		assert_equal(Math.variance(array, undefined, 2, 4), 2/3)
		assert_equal(Math.variance(array, 3, 2, 4), 2/3)
		assert_equal(Math.variance(array, undefined, 4, 4), 0)
	end)
end)
