context("Vector", function()
    test("readonly", function()
        local vec = Vector(0, 1)
        assert_false(vec:isReadonly())
        local vec_readonly = Vector(0, 1, true)
        assert_true(vec_readonly:isReadonly())
    end)

    test("constructor", function()
        local vec = Vector(1, 2)
        assert_equal(vec.x, 1)
        assert_equal(vec.y, 2)
    end)
end)
