/compile_commands.json
/bin
/build*
/.git
/.idea
/.dockerignore
/.gitignore
/.gitlab-ci.yml
/.gitmodules
/Dockerfile
/README.md
/COMPILE.md
/autoref
/docs
/libs
/strategy
/data
!/data/pkg
!/data/docker/simulatorcli_entrypoint.bash

# vim: filetype=gitignore
