local geom = require "../base/geom"

return function()
context("A context", function()
	before(function() end)
	after(function() end)
	context("A nested context", function()
	test("A test", function()
		assert_has_errors(function() error("this should fail") end)
	end)
	context("Another nested context", function()
		test("Another test", function()
			assert_greater_than(2, 1)
		end)
	end)
	end)
	test("A test in the top-level context", function()
		assert_equal(3, 1)
	end)
	test("geom test", function()
		local ret, l1, l2 = geom.intersectLineLine(Vector.create(0, 0), Vector.create(0, 1), Vector.create(0, 1), Vector.create(0, -1))
		assert_equal(ret, Vector.create(0, 0))
		assert_equal(l1, 0)
		assert_equal(l2, 0)
		
		local ret, l1, l2 = geom.intersectLineLine(Vector.create(0, 0), Vector.create(0, 1), Vector.create(0.1, 1), Vector.create(0, -1))
		assert_equal(ret, nil)
		assert_equal(l1, nil)
		assert_equal(l2, nil)
		
		local ret, l1, l2 = geom.intersectLineLine(Vector.create(0, 0), Vector.create(0, 1), Vector.create(1, 1), Vector.create(1, 0))
		assert_equal(ret, Vector.create(0, 1))
		assert_equal(l1, 1)
		assert_equal(l2, -1)
	end)
end)
end
