return function()
context("A context", function()
	before(function() end)
	after(function() end)
	context("A nested context", function()
	test("A test", function()
		assert_has_errors(function() error("this should fail") end)
	end)
	context("Another nested context", function()
		test("Another test", function()
			assert_greater_than(2, 1)
		end)
	end)
	end)
	test("A test in the top-level context", function()
		assert_equal(3, 1)
	end)
end)
end